---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Playbook for deploying horizon
  hosts: horizon_all
  user: root
  become: true
  gather_facts: true
  pre_tasks:
    - include: create-grant-db.yml
      db_name: "{{ horizon_galera_database }}"
      db_password: "{{ horizon_container_mysql_password }}"
  post_tasks:
    - name: Ensure nova service
      keystone:
        command: "ensure_service"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        service_name: "{{ nova_service_name }}"
        service_type: "{{ nova_service_type }}"
        description: "{{ nova_service_description }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      register: add_service
      until: add_service|success
      retries: 5
      delay: 2
    - name: Ensure nova endpoint
      keystone:
        command: "ensure_endpoint"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        region_name: "{{ nova_service_region }}"
        service_name: "{{ nova_service_name }}"
        service_type: "{{ nova_service_type }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
        endpoint_list:
          - url: "{{ nova_service_publicurl }}"
            interface: "public"
          - url: "{{ nova_service_internalurl }}"
            interface: "internal"
          - url: "{{ nova_service_adminurl }}"
            interface: "admin"
      register: add_service
      until: add_service|success
      retries: 5
      delay: 10
  roles:
    - role: "{{ horizon_rolename | default('os_horizon') }}"
  vars_files:
    - test-vars.yml
